### PR TITLE
Refactor FQN to prevent collisions with previous mdr/scalariform version

### PR DESCRIPTION
**Pull request by daniel-trinh**
#40

### CODE REVIEW

**Comment by daniel-trinh** [comment]
@fommil Want to take a look at this PR? 

This is also currently published to Sonatype under `0.1.6-SNAPSHOT`, and a refactored sbt-scalariform is published under `1.3.1-SNAPSHOT`

**Comment by fommil** [comment]
excellent, thank you! I just updated the FQN refs in our codebase and everything worked great.

I assume you'll release a 2.10 and 2.11 version. I only checked this with 2.11. Can you please release a 2.9 build, as we have to release a 2.9 branch of ENSIME to support older projects (we're dropping the support after v1.0, so no need to continue supporting this).

**Comment by fommil** [comment]
did you get any response on publishing to sonatype on org.scalariform ? I suspect it's just a case of pestering him until he gets round to doing it. He seems busy.

**Comment by daniel-trinh** [comment]
Nope.. no response, I'm most likely going to move forward with this code for now, and perhaps undo this change if things change on his end at some point.

**Comment by fommil** [comment]
@daniel-trinh I think that sounds sensible. When we do finally get you sonatype access, you can start to publish there and then release a stub under your name that simply pulls in `org.sonatype`. There won't be many people using the programmatic API (probably just ENSIME/scala-ide I would guess) so we will be happy to change our code :smile: 

Please let me know when you promote to central, and if you have plans for a scala-2.9 backport (I can help if needed)

**Comment by daniel-trinh** [comment]
@fommil I now should have publish permissions to `org.scalariform`. Does this mean this FQN refactor code can be undone so long as I point my code to publish to `org.scalariform` instead of `com.danieltrinh`?

**Comment by fommil** [comment]
@daniel-trinh AWESOME! :smile:

Absolutely, no need to do this FQN renaming. So what I'd recommend is:

1. publish new scalariform for scala 2.9.2, 2.9.3, 2.10, 2.11 (ideally address #29 so that upgrading users don't get new reformatting forced upon them... I'm actually ok with it)
2. publish sbt-scalariform
3. publish pom-only (or ivy-only) dummy packages of the same, under your personal namespace, that simply depend on the official versions. That way everybody gets moved onto the official version.

**Pull request merged**
